name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt install make clang libvulkan-dev libgtk-3-dev --yes --quiet
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Build engine test (cube)
      working-directory: base/tests/cube
      run: ../../../base/make --compile
    - name: Build engine test (fall)
      working-directory: base/tests/fall
      run: ../../../base/make --compile
    - name: Build engine test (triangle)
      working-directory: base/tests/triangle
      run: ../../../base/make --compile
