name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt install make clang libvulkan-dev libgtk-3-dev --yes --quiet
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Build engine test (cube)
      run: cd base/tests/cube && ../../../base/make --compile
    - name: Build engine test (fall)
      run: cd base/tests/fall && ../../../base/make --compile
    - name: Build engine test (triangle)
      run: cd base/tests/triangle && ../../../base/make --compile
    - name: Upload paint build
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: armorpaint-linux-vulkan
        path: paint/build/
        if-no-files-found: warn
        retention-days: 7
