name: Windows (Direct3D12)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
    - name: Build engine test (cube)
      working-directory: base/tests/cube
      run: ../../../base/make --compile
    - name: Build engine test (fall)
      working-directory: base/tests/fall
      run: ../../../base/make --compile
    - name: Build engine test (triangle)
      working-directory: base/tests/triangle
      run: ../../../base/make --compile
